services:
  - type: web
    name: pedlet-flask-postgres
    runtime: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_UPLOAD_MB
        value: 30
